# Generated by Django 2.2.5 on 2023-11-02 01:55

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('issue', models.IntegerField(max_length=100)),
                ('description', models.TextField(blank=True, default='', max_length=300)),
            ],
            managers=[
                ('addComics', django.db.models.manager.Manager()),
            ],
        ),
    ]
