# Generated by Django 2.2.5 on 2023-11-02 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarvelComics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='issue',
            field=models.CharField(max_length=100),
        ),
    ]
